import os
import json
import logging
import asyncio
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

logger = logging.getLogger("SemanticCompiler")

class SemanticCompiler:
    """
    🧩 [WK-401] Semantic Compiler Agent.
    Trasforma le entità estratte da Agent007 in pagine Wiki strutturate (Semantic Atoms).
    Implementa il Karpathy Pattern: Compilazione incrementale anziché semplice recupero.
    """
    def __init__(self, engine):
        self.engine = engine
        self.wiki_dir = Path("vault_data/wiki")
        self.wiki_dir.mkdir(parents=True, exist_ok=True)
        # Sotto-directory per gli Atomi Semantici (Entità)
        self.entity_dir = self.wiki_dir / "entities"
        self.entity_dir.mkdir(parents=True, exist_ok=True)
        
    async def process_new_knowledge(self, node_id: str, entities: List[Dict], relations: List[Dict]):
        """
        Punto di ingresso principale dopo l'estrazione di Agent007.
        """
        if not entities:
            return

        node = self.engine.get_node(node_id)
        if not node:
            return

        logger.info(f"🧩 [WK-401] Compilazione atomi semantici per nodo: {node_id[:8]}")

        for ent in entities:
            name = ent.get('name')
            e_type = ent.get('type', 'Entity')
            if not name or len(name) < 3:
                continue

            # 1. Verifica se l'atomo esiste già
            page_path = self.entity_dir / f"{self._sanitize(name)}.md"
            
            if page_path.exists():
                # 2. Update Incrementale (Compounding)
                await self._update_entity_atom(name, page_path, node, ent, relations)
            else:
                # 3. Creazione Nuovo Atomo
                await self._create_entity_atom(name, e_type, page_path, node, ent, relations)

    async def _create_entity_atom(self, name: str, e_type: str, path: Path, source_node: Any, ent_data: Dict, all_relations: List[Dict]):
        """Crea una nuova pagina Wiki basata sul template Semantic Atom."""
        logger.info(f"🆕 [WK-401] Creazione nuovo Atomo Semantico: {name}")
        
        # Filtriamo le relazioni che riguardano questa entità
        relevant_rels = [r for r in all_relations if r.get('source') == name or r.get('target') == name]
        
        # Generazione contenuto iniziale via LLM per coerenza di stile
        prompt = f"""
        ### TASK: SEMANTIC ATOM COMPILATION (WK-401)
        Sei il compilatore di conoscenza di NeuralVault. Crea una pagina Wiki per l'entità '{name}'.
        
        TIPO: {e_type}
        DATI ESTRATTI: {json.dumps(ent_data)}
        RELAZIONI RILEVATE: {json.dumps(relevant_rels)}
        CONTESTO ORIGINALE: {source_node.text[:500]}
        
        ### REGOLE:
        1. Usa il SOVEREIGN_WIKI_SCHEMA.
        2. Includi sezioni: Executive Summary, Attributes, Relations, Evidence.
        3. Cita SEMPRE la fonte: [CITE:{source_node.id}]
        4. Stile professionale, asciutto, orientato ai dati.
        """
        
        wiki_model = self.engine.orchestrator.settings.get("wiki_model", "qwen2.5:7b")
        content = await self.engine.orchestrator.get_consensus_response(prompt, f"Semantic Compiler: {name}", target_model=wiki_model)
        
        # Frontmatter YAML
        header = f"""---
id: "{source_node.id}"
title: "{name}"
type: "{e_type}"
namespace: "Entities"
version: "1.0.0"
extracted_at: "{datetime.now().isoformat()}"
source_nodes: ["{source_node.id}"]
---

# 🧩 Atomo Semantico: {name.upper()}
> **[🛡️ VERIFIED]** | **[🧬 CATEGORY: {e_type.upper()}]**

{content}

---
*Generated by WK-401 Semantic Compiler on {datetime.now().strftime('%Y-%m-%d')}*
"""
        path.write_text(header, encoding='utf-8')
        
        # Registrazione su Aegis Bus
        if hasattr(self.engine, 'events'):
            self.engine.events.emit_sync("WIKI_GENERATED", {
                "page_name": name,
                "namespace": "Entities",
                "content": header,
                "timestamp": int(time.time())
            })

    async def _update_entity_atom(self, name: str, path: Path, new_node: Any, ent_data: Dict, all_relations: List[Dict]):
        """Aggiorna un atomo esistente con nuove informazioni (Compounding)."""
        logger.info(f"🔄 [WK-401] Aggiornamento compounding per Atomo: {name}")
        
        existing_content = path.read_text(encoding='utf-8')
        relevant_rels = [r for r in all_relations if r.get('source') == name or r.get('target') == name]
        
        prompt = f"""
        ### TASK: COMPOUNDING ATOM UPDATE
        Hai un Atomo Semantico esistente '{name}' e nuovi dati.
        
        CONTENUTO ESISTENTE (Prime 500 parole):
        {existing_content[:500]}
        
        NUOVI DATI: {json.dumps(ent_data)}
        NUOVE RELAZIONI: {json.dumps(relevant_rels)}
        NUOVO CONTESTO: {new_node.text[:400]}
        
        ### REGOLE:
        1. NON riscrivere l'intera pagina.
        2. Aggiungi un blocco ## 📥 Aggiornamento {datetime.now().strftime('%d/%m/%Y')}
        3. Integra nuove relazioni o attributi se non presenti.
        4. Cita: [CITE:{new_node.id}]
        """
        
        wiki_model = self.engine.orchestrator.settings.get("wiki_model", "qwen2.5:7b")
        update_block = await self.engine.orchestrator.get_consensus_response(prompt, f"Compounding Atom: {name}", target_model=wiki_model)
        
        # Append incrementale
        new_content = existing_content.rstrip() + "\n\n" + update_block
        path.write_text(new_content, encoding='utf-8')

    def _sanitize(self, name: str) -> str:
        return "".join([c if c.isalnum() else "_" for c in name])
