import logging
import json
from typing import List, Dict, Any

class WikiVisualizer:
    """
    📊 [v8.0] Phase 7: Generative Multimedia Engine.
    Genera diagrammi Mermaid.js e Timeline interattive basate sulla struttura del Vault.
    """
    def __init__(self, engine):
        self.engine = engine
        self.logger = logging.getLogger("WikiVisualizer")

    def generate_mermaid_flow(self, nodes: List[Any]) -> str:
        """Genera un flowchart Mermaid basato sulle relazioni tra i nodi forniti."""
        if not nodes: return ""
        
        lines = ["graph TD", "    %% Auto-generated by NeuralVault WikiVisualizer"]
        node_ids = {n.id for n in nodes if hasattr(n, 'id')}
        
        for node in nodes:
            # Pulisci il titolo per Mermaid
            clean_title = node.title.replace('"', "'").replace('(', '[').replace(')', ']')
            lines.append(f'    {node.id}["{clean_title}"]')
            
            for edge in node.edges:
                if edge.target_id in node_ids:
                    rel_label = edge.relation.value if hasattr(edge.relation, 'value') else str(edge.relation)
                    arrow = "-->"
                    if rel_label == "PREVENTS": arrow = "---| PREVENTS |x"
                    elif rel_label == "CAUSES": arrow = "== CAUSES ==>"
                    
                    lines.append(f'    {node.id} {arrow} |{rel_label}| {edge.target_id}')
        
        return "\n".join(lines)

    def generate_knowledge_timeline(self, nodes: List[Any]) -> str:
        """Genera un diagramma di timeline Mermaid basato sui metadati temporali."""
        # Filtra nodi con date valide
        dated_nodes = []
        for n in nodes:
            meta = getattr(n, 'metadata', {})
            date = meta.get('date') or meta.get('source_date')
            if date:
                dated_nodes.append((date, n.title))
        
        if not dated_nodes: return ""
        
        # Ordina per data (semplice alfabetico se stringa ISO)
        dated_nodes.sort()
        
        lines = ["timeline", "    title Evolutionary Knowledge Timeline"]
        for date, title in dated_nodes:
            # Raggruppa per anno/mese se possibile
            section = date.split('-')[0] if '-' in date else date
            lines.append(f'    {section} : {title}')
            
        return "\n".join(lines)

    def generate_confidence_dashboard(self, sections_metadata: List[Dict]) -> str:
        """Genera un HUD di riepilogo della fiducia (Epistemic Weather)."""
        avg_conf = sum(s.get('confidence', 0) for s in sections_metadata) / len(sections_metadata) if sections_metadata else 0
        status = "EXCELLENT" if avg_conf > 0.85 else ("STABLE" if avg_conf > 0.65 else "UNSTABLE")
        
        return f"""
<div class="confidence-dashboard">
    <div class="status-badge {status.lower()}">{status}</div>
    <div class="metrics">
        <span>Avg Confidence: {round(avg_conf*100)}%</span>
        <span>Verified Sources: {len([s for s in sections_metadata if s.get('mesh_verified')])}</span>
    </div>
</div>
"""
