import logging
import json
from typing import List, Dict, Any

class WikiVisualizer:
    """
    📊 [v8.0] Phase 7: Generative Multimedia Engine.
    Genera diagrammi Mermaid.js e Timeline interattive basate sulla struttura del Vault.
    """
    def __init__(self, engine):
        self.engine = engine
        self.logger = logging.getLogger("WikiVisualizer")

    def generate_mermaid_flow(self, nodes: List[Any]) -> str:
        """Genera un flowchart Mermaid basato sulle relazioni tra i nodi forniti."""
        if not nodes: return ""
        
        lines = ["graph TD", "    %% Auto-generated by NeuralVault WikiVisualizer"]
        node_ids = {n.id for n in nodes if hasattr(n, 'id')}
        
        for node in nodes:
            # Pulisci il titolo per Mermaid
            clean_title = node.title.replace('"', "'").replace('(', '[').replace(')', ']')
            lines.append(f'    {node.id}["{clean_title}"]')
            
            for edge in node.edges:
                if edge.target_id in node_ids:
                    rel_label = edge.relation.value if hasattr(edge.relation, 'value') else str(edge.relation)
                    arrow = "-->"
                    if rel_label == "PREVENTS": arrow = "---| PREVENTS |x"
                    elif rel_label == "CAUSES": arrow = "== CAUSES ==>"
                    
                    lines.append(f'    {node.id} {arrow} |{rel_label}| {edge.target_id}')
        
        return "\n".join(lines)

    def generate_knowledge_timeline(self, nodes: List[Any]) -> str:
        """Genera un diagramma di timeline Mermaid basato sui metadati temporali."""
        # Filtra nodi con date valide
        dated_nodes = []
        for n in nodes:
            meta = getattr(n, 'metadata', {})
            date = meta.get('date') or meta.get('source_date')
            if date:
                dated_nodes.append((date, n.title))
        
        if not dated_nodes: return ""
        
        # Ordina per data (semplice alfabetico se stringa ISO)
        dated_nodes.sort()
        
        lines = ["timeline", "    title Evolutionary Knowledge Timeline"]
        for date, title in dated_nodes:
            # Raggruppa per anno/mese se possibile
            section = date.split('-')[0] if '-' in date else date
            lines.append(f'    {section} : {title}')
            
        return "\n".join(lines)

    def generate_confidence_dashboard(self, sections_metadata: List[Dict], global_mood: Dict = None) -> str:
        """Genera un HUD di riepilogo della fiducia (Epistemic Weather)."""
        avg_conf = sum(s.get('confidence', 0) for s in sections_metadata) / len(sections_metadata) if sections_metadata else 0
        
        # [v8.4] Epistemic Weather Logic
        if global_mood:
            weather_icon = global_mood.get("mood", "☀️")
            weather_status = global_mood.get("status", "CLEAR_SKY")
            score = global_mood.get("score", avg_conf)
        else:
            # Fallback based on confidence
            if avg_conf > 0.85: weather_icon, weather_status = "☀️", "CLEAR_SKY"
            elif avg_conf > 0.65: weather_icon, weather_status = "🌤️", "PARTLY_CLOUDY"
            elif avg_conf > 0.45: weather_icon, weather_status = "🌥️", "OVERCAST"
            else: weather_icon, weather_status = "🌩️", "STORMY"
            score = avg_conf

        return f"""
<div class="epistemic-weather-hud" style="background: rgba(15, 23, 42, 0.6); backdrop-filter: blur(20px); border: 1px solid rgba(59, 130, 246, 0.2); border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; display: flex; align-items: center; gap: 2rem; box-shadow: 0 10px 30px rgba(0,0,0,0.4);">
    <div class="weather-icon" style="font-size: 3rem; filter: drop-shadow(0 0 10px rgba(59, 130, 246, 0.4));">{weather_icon}</div>
    <div class="weather-info" style="flex: 1;">
        <div style="font-size: 0.6rem; color: #3b82f6; font-weight: 900; letter-spacing: 2px;">EPISTEMIC_WEATHER</div>
        <div style="font-size: 1.2rem; font-weight: 800; color: #fff;">{weather_status.replace('_', ' ')}</div>
        <div style="font-size: 0.7rem; color: #94a3b8; margin-top: 4px;">Knowledge Integrity Score: <span style="color: #4ade80; font-weight: 800;">{round(score*100)}%</span></div>
    </div>
    <div class="weather-stats" style="display: flex; gap: 1.5rem; border-left: 1px solid rgba(255,255,255,0.05); padding-left: 2rem;">
        <div class="stat-item">
            <div style="font-size: 0.5rem; color: #64748b; text-transform: uppercase;">Confidence</div>
            <div style="font-size: 0.9rem; color: #fff; font-weight: 700;">{round(avg_conf*100)}%</div>
        </div>
        <div class="stat-item">
            <div style="font-size: 0.5rem; color: #64748b; text-transform: uppercase;">Source Nodes</div>
            <div style="font-size: 0.9rem; color: #fff; font-weight: 700;">{len(sections_metadata)}</div>
        </div>
    </div>
</div>
"""
